### ISSUE TITLE
visualisation -> visualization

### ISSUE THREAD

**Issue by vovanmozg** [UDST/vizicities#163]
misprint on main page https://github.com/UDST/vizicities

**Comment by waddell** [comment]
Fixed.

**Comment by robhawkes** [comment]
@vovanmozg thanks for pointing this out – I'm English so you'll have to excuse some of the differences in spelling. We're currently discussing how to approach using a single language / way of spelling across ViziCities so this'll be cleared up one way or the other in the near future.
