### ISSUE TITLE
Does vizicities uses its own map engine?

### ISSUE THREAD

**Issue by am2222** [UDST/vizicities#187]
Hi,
I want to know if vizicities uses its own map engine or can we add it as an extra layer on openlayers or leaflet?
thanks

**Comment by robhawkes** [comment]
Hi @am2222, sorry for the delay!

ViziCities uses it's own map engine built on top of the three.js WebGL library. While the API is similar to that of Leaflet you wouldn't be able to use it as a layer within a Leaflet map. For that, you'll want to look at something like [Tangram](https://github.com/tangrams/tangram).
